### ISSUE TITLE
Question about env.

### ISSUE THREAD

**Issue by dukebarman** [dan-da/php2js#1]
What environment do you use for php2js (OS, version of boost, php, ...)? Author of  PHC PHP Compiler said that his project is no longer developed (https://github.com/pbiggar/phc/issues/163) and I have troubles with phc install

**Comment by dan-da** [comment]
I am using Ubuntu 14.04.   I actually haven't done a PHC install in a very long time.  

My version is phc 0.2.0rc1.

I will attempt a phc install and see what happens.

**Comment by dan-da** [comment]
Ok, I ran into some problems compiling PHC also.   The 0.3.x versions give me configure problems that I couldn't immediately resolve.

The 0.2.x versions configure ok (once dependencies are installed) but give a compile error that I was able to resolve.

Here's a formula that seems to work on ubuntu 14.04 (and probably later versions):

sudo apt-get install build-essential libboost-dev libxerces-c-dev graphviz libgc-dev

wget "http://www.phpcompiler.org/src/archive/phc-0.2.0-alpha1.tar.gz"
tar -xzvf phc-0.2.0-alpha1.tar.gz
cd phc-0.2.0-alpha1
./configure

edit file src/lib/List.h
add this line:
        using list<_Tp, _Alloc>::insert;
after line:
        using list<_Tp, _Alloc>::push_back;

make
make install

Probably the later 0.2.x series will also build, but I haven't tried them yet.

Please let me know how it goes.  If you are successful I will add instructions to the readme.

**Comment by dan-da** [comment]
scratch that.  I posted my comment too early.  ran into more compile issues.  more later.

**Comment by dan-da** [comment]
bummer.  I ran into an error I'm not sure how to resolve.

```
 g++ -DHAVE_CONFIG_H -I. -I./libltdl -I./src -I./3rdparty/getopt -I./src/generated -DDATADIR=\"/usr/local/share\" -DPKGLIBDIR=\"/usr/local/lib/phc\" -Wall -Wextra -Wno-unused-parameter -Wno-write-strings -g -O2 -MT XML_parser.lo -MD -MP -MF .deps/XML_parser.Tpo -c src/parsing/XML_parser.cpp  -fPIC -DPIC -o .libs/XML_parser.o

In file included from src/parsing/XML_parser.cpp:8:0:
src/parsing/XML_parser.h: In member function 'virtual void PHC_SAX2Handler::startElement(const XMLCh*, const XMLCh*, const XMLCh*, const xercesc_3_1::Attributes&)':
src/parsing/XML_parser.h:254:32: error: invalid use of incomplete type 'const class xercesc_3_1::Attributes'
   for(unsigned i = 0; i < attrs.getLength(); i++)

```

**Comment by dukebarman** [comment]
:'( I've a problem with boost library. May be create docker image for that?
